import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import { NanumGothicBase64 } from "./fonts/NanumGothicBase64"

interface QuoteItem {
  product: {
    name: string
    brand: string
    category: {
      name: string
    }
  }
  quantity: number
  originalPrice: number
  quotedPrice: number
}

interface QuotePDFData {
  quoteNumber: string
  createdAt: string
  validUntil: string
  customer: {
    name: string | null
    email: string
    phone: string | null
    address: string | null
  }
  salesManager: {
    name: string | null
    email: string
    phone: string | null
  }
  items: QuoteItem[]
  originalAmount: number
  discountAmount: number
  totalAmount: number
  notes: string | null
  status: string
}

export function generateQuotePDF(data: QuotePDFData, mode: 'download' | 'preview' = 'download'): string | void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  // 나눔고딕 폰트를 jsPDF에 추가하여 한글 지원
  try {
    doc.addFileToVFS("NanumGothic.ttf", NanumGothicBase64)
    doc.addFont("NanumGothic.ttf", "NanumGothic", "normal")
    doc.setFont("NanumGothic", "normal")
  } catch (error) {
    console.error("한글 폰트 로드 실패:", error)
    // 폰트 로드 실패 시 기본 폰트 사용
    doc.setFont("helvetica", "normal")
  }

  // 제목
  doc.setFontSize(20)
  doc.text("QUOTE / ESTIMATE", 105, 20, { align: "center" })
  doc.setFontSize(16)
  doc.text(data.quoteNumber, 105, 28, { align: "center" })

  // 견적서 정보
  doc.setFontSize(10)
  doc.text(`Date: ${new Date(data.createdAt).toLocaleDateString("ko-KR")}`, 14, 40)
  doc.text(`Valid Until: ${new Date(data.validUntil).toLocaleDateString("ko-KR")}`, 14, 46)
  doc.text(`Status: ${getStatusLabel(data.status)}`, 14, 52)

  // 고객 정보
  doc.setFontSize(12)
  doc.setFont("helvetica", "bold")
  doc.text("Customer Information", 14, 65)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.text(`Name: ${data.customer.name || "N/A"}`, 14, 72)
  doc.text(`Email: ${data.customer.email}`, 14, 78)
  if (data.customer.phone) {
    doc.text(`Phone: ${data.customer.phone}`, 14, 84)
  }
  if (data.customer.address) {
    doc.text(`Address: ${data.customer.address}`, 14, 90)
  }

  // 영업매니저 정보
  doc.setFontSize(12)
  doc.setFont("helvetica", "bold")
  doc.text("Sales Manager", 120, 65)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.text(`Name: ${data.salesManager.name || "N/A"}`, 120, 72)
  doc.text(`Email: ${data.salesManager.email}`, 120, 78)
  if (data.salesManager.phone) {
    doc.text(`Phone: ${data.salesManager.phone}`, 120, 84)
  }

  // 견적 항목 테이블
  const tableData = data.items.map((item) => [
    `${item.product.name}\n${item.product.brand} - ${item.product.category.name}`,
    item.quantity.toString(),
    formatPrice(item.originalPrice),
    formatPrice(item.quotedPrice),
    formatPrice(item.quotedPrice * item.quantity),
  ])

  autoTable(doc, {
    startY: 100,
    head: [["Product", "Qty", "Original Price", "Quoted Price", "Total"]],
    body: tableData,
    theme: "grid",
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: 255,
      fontStyle: "bold",
      font: "NanumGothic",
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
      font: "NanumGothic",
    },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 20, halign: "center" },
      2: { cellWidth: 30, halign: "right" },
      3: { cellWidth: 30, halign: "right" },
      4: { cellWidth: 35, halign: "right" },
    },
  })

  // 총액 정보
  const finalY = (doc as any).lastAutoTable.finalY + 10
  doc.setFontSize(10)
  doc.text("Original Amount:", 130, finalY)
  doc.text(formatPrice(data.originalAmount) + " KRW", 195, finalY, { align: "right" })

  doc.setTextColor(220, 53, 69)
  doc.text("Discount:", 130, finalY + 6)
  doc.text("-" + formatPrice(data.discountAmount) + " KRW", 195, finalY + 6, { align: "right" })

  doc.setTextColor(0, 0, 0)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(12)
  doc.text("Total Amount:", 130, finalY + 14)
  doc.setTextColor(40, 167, 69)
  doc.text(formatPrice(data.totalAmount) + " KRW", 195, finalY + 14, { align: "right" })

  // 메모
  if (data.notes) {
    doc.setTextColor(0, 0, 0)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(11)
    doc.text("Notes:", 14, finalY + 28)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    const splitNotes = doc.splitTextToSize(data.notes, 180)
    doc.text(splitNotes, 14, finalY + 34)
  }

  // 푸터
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(8)
  doc.setTextColor(128, 128, 128)
  doc.text("Generated by Ultra System", 105, pageHeight - 10, { align: "center" })

  // PDF 다운로드 또는 미리보기용 데이터 URL 반환
  if (mode === 'preview') {
    return doc.output('dataurlstring')
  } else {
    doc.save(`${data.quoteNumber}.pdf`)
  }
}

function formatPrice(price: number): string {
  return new Intl.NumberFormat("ko-KR").format(price)
}

function getStatusLabel(status: string): string {
  switch (status) {
    case "PENDING":
      return "Pending"
    case "SENT":
      return "Sent"
    case "APPROVED":
      return "Approved"
    case "REJECTED":
      return "Rejected"
    case "EXPIRED":
      return "Expired"
    case "ORDERED":
      return "Ordered"
    default:
      return status
  }
}
